### ISSUE TITLE
AttributeError: 'str' object has no attribute 'c'

### ISSUE THREAD

**Issue by jiangyd** [mitsuhiko/flask-sqlalchemy#559]
```python
from flask import Flask

from flask_sqlalchemy import SQLAlchemy

import pymysql

app = Flask(__name__)

app.config["SQLALCHEMY_DATABASE_URI"] = "mysql+pymysql://root:123456@192.168.56.102:3377/movie"
app.config["SQLALCHEMY_TRACK_MODIFICATIONS"] = True

db = SQLAlchemy(app)


class Userteb(db.Model):
    __table__ = "userteb"
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(80), unique=True, nullable=False)
    email = db.Column(db.String(120), unique=True, nullable=False)

    def __repr__(self):
        return '<User %r>' % self.username


if __name__ == "__main__":
    db.create_all()
```

```
(python3_zy) jiangyd:app jiangyd$ python mm.py 
Traceback (most recent call last):
  File "mm.py", line 15, in <module>
    class Userteb(db.Model):
  File "/Users/jiangyd/python3_zy/lib/python3.6/site-packages/flask_sqlalchemy/model.py", line 67, in __init__
    super(NameMetaMixin, cls).__init__(name, bases, d)
  File "/Users/jiangyd/python3_zy/lib/python3.6/site-packages/flask_sqlalchemy/model.py", line 112, in __init__
    super(BindMetaMixin, cls).__init__(name, bases, d)
  File "/Users/jiangyd/python3_zy/lib/python3.6/site-packages/sqlalchemy/ext/declarative/api.py", line 64, in __init__
    _as_declarative(cls, classname, cls.__dict__)
  File "/Users/jiangyd/python3_zy/lib/python3.6/site-packages/sqlalchemy/ext/declarative/base.py", line 88, in _as_declarative
    _MapperConfig.setup_mapping(cls, classname, dict_)
  File "/Users/jiangyd/python3_zy/lib/python3.6/site-packages/sqlalchemy/ext/declarative/base.py", line 103, in setup_mapping
    cfg_cls(cls_, classname, dict_)
  File "/Users/jiangyd/python3_zy/lib/python3.6/site-packages/sqlalchemy/ext/declarative/base.py", line 131, in __init__
    self._setup_table()
  File "/Users/jiangyd/python3_zy/lib/python3.6/site-packages/sqlalchemy/ext/declarative/base.py", line 400, in _setup_table
    if not table.c.contains_column(c):
AttributeError: 'str' object has no attribute 'c'
```

**Comment by ThiefMaster** [comment]
You need `__tablename__`, not `__table__` (which would have to be a Table instance).

**Comment by jiangyd** [comment]
sorry,I thought I found a bug，i see this http://flask-sqlalchemy.pocoo.org/2.3/api/?highlight=__table__

__tablename__
The name of the table in the database. This is required by SQLAlchemy; however, Flask-SQLAlchemy will set it automatically if a model has a primary key defined. If the __table__ or __tablename__ is set explicitly, that will be used instead.

**Comment by ThiefMaster** [comment]
Sounds correct to me. `__tablename__` is the table name, and `__table__` is not documented in this  place since it's rarely needed and actually just [SQLAlchemy functionality](http://docs.sqlalchemy.org/en/latest/orm/extensions/declarative/table_config.html#using-a-hybrid-approach-with-table). The docs here simply mention that using either will disable auto tablename generation for the model

**Comment by jiangyd** [comment]
thanks for your help

**Comment by alorwu** [comment]
thanks for pointing that out @ThiefMaster great answer
