### ISSUE TITLE
Selecting Object from existing DB results in Invalid Object

### ISSUE THREAD

**Issue by ledikari** [mitsuhiko/flask-sqlalchemy#571]
running the following code on flask by going on the route /getAllUsers,  it yields an error : Invalid Object name, here is the snippet of the code.

```
class User(db.Model):
    #table name is RCA.MyLogin
    __tablename__ = 'RCA.MyLogin'
    id = db.Column('ID', db.Integer, primary_key=True)
    UName = db.Column('UName', db.String(255))
    Pass = db.Column('Pass', db.String(255))
    
@app.route('/getAllusers', methods=['GET'])
def get_all_users():
    users = User.query.all()
    output = []

    for user in users:
        user_data = dict()
        user_data['UName'] = user.Uname
        user_data['Pass'] = user.Pass
        output.append(user_data)

    return jsonify({'users': output})
```

what might be the possible cause? I tried creating simple connect through sqlalchemy with 'Select * from RCA.MyLogin' and 'it works, but when i use it with flask-sqlalchemy yields an error.

**Comment by ThiefMaster** [comment]
Error reports without proper exception messages and tracebacks are kind of useless.

**Comment by ledikari** [comment]
sorry, here is the exception messges

```
Traceback (most recent call last):
  File "C:\Python\Python36\lib\site-packages\flask\app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Python\Python36\lib\site-packages\flask\app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Python\Python36\lib\site-packages\flask\app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python\Python36\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "C:\Python\Python36\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python\Python36\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python\Python36\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python\Python36\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "C:\Python\Python36\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python\Python36\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Python\Scripts\BCAMicroService\BCAMicroService.py", line 54, in get_all_users
    users = User.query.all()
  File "C:\Python\Python36\lib\site-packages\sqlalchemy\orm\query.py", line 2703, in all
    return list(self)
  File "C:\Python\Python36\lib\site-packages\sqlalchemy\orm\query.py", line 2855, in __iter__
    return self._execute_and_instances(context)
  File "C:\Python\Python36\lib\site-packages\sqlalchemy\orm\query.py", line 2878, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "C:\Python\Python36\lib\site-packages\sqlalchemy\engine\base.py", line 945, in execute
    return meth(self, multiparams, params)
  File "C:\Python\Python36\lib\site-packages\sqlalchemy\sql\elements.py", line 263, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "C:\Python\Python36\lib\site-packages\sqlalchemy\engine\base.py", line 1053, in _execute_clauseelement
    compiled_sql, distilled_params
  File "C:\Python\Python36\lib\site-packages\sqlalchemy\engine\base.py", line 1189, in _execute_context
    context)
  File "C:\Python\Python36\lib\site-packages\sqlalchemy\engine\base.py", line 1402, in _handle_dbapi_exception
    exc_info
  File "C:\Python\Python36\lib\site-packages\sqlalchemy\util\compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "C:\Python\Python36\lib\site-packages\sqlalchemy\util\compat.py", line 186, in reraise
    raise value.with_traceback(tb)
  File "C:\Python\Python36\lib\site-packages\sqlalchemy\engine\base.py", line 1182, in _execute_context
    context)
  File "C:\Python\Python36\lib\site-packages\sqlalchemy\engine\default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (pyodbc.ProgrammingError) ('42S02', "[42S02] [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Invalid object name 'RCA.MyLogin'. (208) (SQLExecDirectW)") [SQL: 'SELECT [RCA.MyLogin].[ID] AS [RCA.MyLogin_ID], [RCA.MyLogin].[Chk_Username] AS [RCA.MyLogin_Chk_Username], [RCA.MyLogin].[Chk_Password] AS [RCA.MyLogin_Chk_Password], [RCA.MyLogin].[Chk_Name] AS [RCA.MyLogin_Chk_Name], [RCA.MyLogin].[Chk_Position] AS [RCA.MyLogin_Chk_Position], [RCA.MyLogin].[Chk_Access_Level] AS [RCA.MyLogin_Chk_Access_Level], [RCA.MyLogin].[Chk_Email_Address] AS [RCA.MyLogin_Chk_Email_Address] \nFROM [RCA.MyLogin]']
```

**Comment by ThiefMaster** [comment]
RCA is most likely a schema and not part of the table name, so you need this:

```python
 __tablename__ = 'MyLogin'
__table_args__ = {'schema': 'RCA'}
```
