### ISSUE TITLE
Cannot configure port param in 'SQLALCHEMY_DATABASE_URI'

### ISSUE THREAD

**Issue by epicGeek** [mitsuhiko/flask-sqlalchemy#612]
So I have a problem during configuring my port param,
`app.config['SQLALCHEMY_DATABASE_URI'] = 'mysql://root:root@localhost/kata' # everything is ok!`

`app.config['SQLALCHEMY_DATABASE_URI'] = 'mysql://root:root@localhost:3306/kata #exception'`

LOG:
```
D:\Tools\Anaconda2\python.exe C:/Users/neilpei/PycharmProjects/neil-test/sql-port.py
Traceback (most recent call last):
  File "C:/Users/neilpei/PycharmProjects/neil-test/sql-port.py", line 22, in <module>
    db.create_all()
  File "D:\Tools\Anaconda2\lib\site-packages\flask_sqlalchemy\__init__.py", line 963, in create_all
    self._execute_for_all_tables(app, bind, 'create_all')
  File "D:\Tools\Anaconda2\lib\site-packages\flask_sqlalchemy\__init__.py", line 955, in _execute_for_all_tables
    op(bind=self.get_engine(app, bind), **extra)
  File "D:\Tools\Anaconda2\lib\site-packages\sqlalchemy\sql\schema.py", line 3949, in create_all
    tables=tables)
  File "D:\Tools\Anaconda2\lib\site-packages\sqlalchemy\engine\base.py", line 1928, in _run_visitor
    with self._optional_conn_ctx_manager(connection) as conn:
  File "D:\Tools\Anaconda2\lib\contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "D:\Tools\Anaconda2\lib\site-packages\sqlalchemy\engine\base.py", line 1921, in _optional_conn_ctx_manager
    with self.contextual_connect() as conn:
  File "D:\Tools\Anaconda2\lib\site-packages\sqlalchemy\engine\base.py", line 2112, in contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
  File "D:\Tools\Anaconda2\lib\site-packages\sqlalchemy\engine\base.py", line 2147, in _wrap_pool_connect
    return fn()
  File "D:\Tools\Anaconda2\lib\site-packages\sqlalchemy\pool.py", line 387, in connect
    return _ConnectionFairy._checkout(self)
  File "D:\Tools\Anaconda2\lib\site-packages\sqlalchemy\pool.py", line 766, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "D:\Tools\Anaconda2\lib\site-packages\sqlalchemy\pool.py", line 516, in checkout
    rec = pool._do_get()
  File "D:\Tools\Anaconda2\lib\site-packages\sqlalchemy\pool.py", line 1138, in _do_get
    self._dec_overflow()
  File "D:\Tools\Anaconda2\lib\site-packages\sqlalchemy\util\langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "D:\Tools\Anaconda2\lib\site-packages\sqlalchemy\pool.py", line 1135, in _do_get
    return self._create_connection()
  File "D:\Tools\Anaconda2\lib\site-packages\sqlalchemy\pool.py", line 333, in _create_connection
    return _ConnectionRecord(self)
  File "D:\Tools\Anaconda2\lib\site-packages\sqlalchemy\pool.py", line 461, in __init__
    self.__connect(first_connect_check=True)
  File "D:\Tools\Anaconda2\lib\site-packages\sqlalchemy\pool.py", line 651, in __connect
    connection = pool._invoke_creator(self)
  File "D:\Tools\Anaconda2\lib\site-packages\sqlalchemy\engine\strategies.py", line 105, in connect
    return dialect.connect(*cargs, **cparams)
  File "D:\Tools\Anaconda2\lib\site-packages\sqlalchemy\engine\default.py", line 393, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "D:\Tools\Anaconda2\lib\site-packages\MySQLdb\__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "D:\Tools\Anaconda2\lib\site-packages\MySQLdb\connections.py", line 193, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
TypeError: an integer is required
```

my version info:
python:2.7.14
flask: 0.12.2
flask-sqlalchemy:2.3.2
mysql-python:1.2.5

I use anaconda by the way.

I don't believe that flask-sqlalchemy do not support to customize port .There must be something wrong with my configure.But I didn't get answer by googling.  Sorry if this is a stupid issue.

**Comment by alanhamlett** [comment]
Does it happen with CPython instead of Anaconda? You can download it here:
https://www.python.org/downloads/

**Comment by epicGeek** [comment]
@alanhamlett  My python.exe is here : D:/Tools/Anaconda2/python.exe  looks like it was in anaconda.I debugged the code ,in connection.py, the variable port was a string type instead of int.I don't know how can I fix it.I must use anaconda.And I upgrade python to 2.7.14.Now I give up using flask-sqlachemy and I start to learn sqlachemy.
This code actually works.
`engine = create_engine('mysql://root:root@localhost:3306/egp',echo = True)`

**Comment by epicGeek** [comment]
It seems that the issue has been solved.
I update anaconda : `conda upgrade conda` and then It is ok.
