### ISSUE TITLE
Inconsistent performance when using factory mode and normal mode.

### ISSUE THREAD

**Issue by garenchan** [mitsuhiko/flask-sqlalchemy#642]
When using normal mode, we can successfully get the engine.
```
from flask import Flask
from flask_sqlalchemy import SQLAlchemy

app = Flask(__name__)
# add some configurations.
db = SQLAlchemy(app)
print(db.engine)
```
But when using factory mode, a **RuntimeError** raised.
```
from flask import Flask
from flask_sqlalchemy import SQLAlchemy

app = Flask(__name__)
# add some configurations.
db = SQLAlchemy()
db.init_app(app)
print(db.engine)
```
The traceback is as follows:
```
Traceback (most recent call last):
  File "test.py", line 17, in <module>
    print(db.engine)
  File "E:\.venv\lib\site-packages\flask_sqlalchemy\__init__.py", line 877, in engine
    return self.get_engine()
  File "E:\.venv\lib\site-packages\flask_sqlalchemy\__init__.py", line 886, in get_engine
    app = self.get_app(app)
  File "E:\.venv\lib\site-packages\flask_sqlalchemy\__init__.py", line 912, in get_app
    'No application found. Either work inside a view function or push'
RuntimeError: No application found. Either work inside a view function or push an application context. See http://flask-sqlalchemy.pocoo.org/contexts/.
```

**Comment by ThiefMaster** [comment]
When using `init_app` you need to have an active Flask app context to use the extension.
